# This is an autogenerated function, ported from the original legacy version.
# It /should work/ as is, but will not have all the benefits of the modern
# function API. You should see the function docs to learn how to add function
# signatures for type safety and to document this function using puppet-strings.
#
# https://puppet.com/docs/puppet/latest/custom_functions_ruby.html
#
# ---- original file header ----
require 'json'

# ---- original file header ----
#
# @summary
#   Generates configuration for Mesos domains
#
#
Puppet::Functions.create_function(:'dcos::dcos_domain') do
  # @param arguments
  #   The original array of arguments. Port this to individually managed params
  #   to get the full benefit of the modern function API.
  #
  # @return [Data type]
  #   Describe what the function returns here
  #
  dispatch :default_impl do
    # Call the method named 'default_impl' when this is matched
    # Port this to match individual params for better type safety
    repeated_param 'Any', :arguments
  end


  def default_impl(*arguments)
    

    raise(Puppet::ParseError, "dcos_domain(): Wrong number of arguments " +
      "given (#{arguments.size} for 2)") if arguments.size != 2

    region = arguments[0]
    zone = arguments[1]
    conf = {"fault_domain" => {}}

    if region
      conf["fault_domain"]["region"] = {"name" => region}
    end

    if zone
      conf["fault_domain"]["zone"] = {"name" => zone}
    end
    return conf.to_json
  
  end
end
